[project]
name = "docs"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "mkdocs-git-committers-plugin-2>=2.4.1",
    "mkdocs-git-revision-date-localized-plugin>=1.3.0",
    "mkdocs-material>=9.5.49",
]
